export {
  LOCAL_STATE_QUERY,
  ALL_ITEMS_QUERY,
  SINGLE_ORDER_QUERY,
  USER_ORDERS_QUERY,
  PAGINATION_QUERY,
  ALL_USERS_QUERY,
  SEARCH_ITEMS_QUERY,
  SINGLE_ITEM_QUERY,
  CURRENT_USER_QUERY
} from './Queries';